# Databricks notebook source
import pandas as pd
import io
db_output = dbutils.widgets.get("db_output")

# COMMAND ----------

#mhsds count suppression function
#counts at sub-national level need to be suppressed
def suppress(x, base=5):   
    if x < 5:
        return '*'
    else:
        return int(base * round(float(x)/base))
spark.udf.register("suppress", suppress)

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.org_type;
 CREATE TABLE IF NOT EXISTS $db_output.org_type
 ---table which gives the provider type for each organisation
 (
 ORG_CODE string,
 ORG_NAME string,
 ORG_TYPE string ---nhs mental health and learning disabilities trust or nhs acute trust or independent provider
 )

# COMMAND ----------

#raw data to be inserted into $db_output.org_type
data = """ORG_CODE,ORG_NAME,ORG_TYPE
RBS,ALDER HEY CHILDREN'S NHS FOUNDATION TRUST,MH & LD
RVN,AVON AND WILTSHIRE MENTAL HEALTH PARTNERSHIP NHS TRUST,MH & LD
RRP,"BARNET, ENFIELD AND HARINGEY MENTAL HEALTH NHS TRUST",MH & LD
RWX,BERKSHIRE HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RXT,BIRMINGHAM AND SOLIHULL MENTAL HEALTH NHS FOUNDATION TRUST,MH & LD
TAJ,BLACK COUNTRY PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
TAD,BRADFORD DISTRICT CARE TRUST,MH & LD
RT1,CAMBRIDGESHIRE AND PETERBOROUGH NHS FOUNDATION TRUST,MH & LD
TAF,CAMDEN AND ISLINGTON NHS FOUNDATION TRUST,MH & LD
RV3,CENTRAL AND NORTH WEST LONDON NHS FOUNDATION TRUST,MH & LD
RXA,CHESHIRE AND WIRRAL PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RJ8,CORNWALL PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RYG,COVENTRY AND WARWICKSHIRE PARTNERSHIP NHS TRUST,MH & LD
RY8,DERBYSHIRE COMMUNITY HEALTH SERVICES NHS FOUNDATION TRUST,MH & LD
RXM,DERBYSHIRE HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RWV,DEVON PARTNERSHIP NHS TRUST,MH & LD
RWK,EAST LONDON NHS FOUNDATION TRUST,MH & LD
R1L,ESSEX PARTNERSHIP UNIVERSITY FOUNDATION TRUST,MH & LD
RTQ,GLOUCESTERSHIRE HEALTH AND CARE NHS FOUNDATION TRUST,MH & LD
RXV,GREATER MANCHESTER MENTAL HEALTH NHS FOUNDATION TRUST,MH & LD
RWR,HERTFORDSHIRE PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST,MH & LD
RV9,HUMBER NHS FOUNDATION TRUST,MH & LD
R1F,ISLE OF WIGHT NHS TRUST,MH & LD
RXY,KENT AND MEDWAY NHS AND SOCIAL CARE PARTNERSHIP TRUST,MH & LD
RW5,LANCASHIRE CARE NHS FOUNDATION TRUST,MH & LD
RGD,LEEDS AND YORK PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RY6,LEEDS COMMUNITY HEALTHCARE NHS TRUST,MH & LD
RT5,LEICESTERSHIRE PARTNERSHIP NHS TRUST,MH & LD
RP7,LINCOLNSHIRE PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
R0A,MANCHESTER UNIVERSITY NHS FOUNDATION TRUST,MH & LD
RW4,MERSEY CARE NHS TRUST,MH & LD
RMY,NORFOLK AND SUFFOLK NHS FOUNDATION TRUST,MH & LD
RAT,NORTH EAST LONDON NHS FOUNDATION TRUST,MH & LD
RLY,NORTH STAFFORDSHIRE COMBINED HEALTHCARE NHS TRUST,MH & LD
RTV,NORTH WEST BOROUGHS HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RP1,NORTHAMPTONSHIRE HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RX4,"NORTHUMBERLAND, TYNE AND WEAR NHS FOUNDATION TRUST",MH & LD
RTF,NORTHUMBRIA HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RHA,NOTTINGHAMSHIRE HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RNU,OXFORD HEALTH NHS FOUNDATION TRUST,MH & LD
RPG,OXLEAS NHS FOUNDATION TRUST,MH & LD
RT2,PENNINE CARE NHS FOUNDATION TRUST,MH & LD
RXE,ROTHERHAM DONCASTER AND SOUTH HUMBER NHS FOUNDATION TRUST,MH & LD
RCU,SHEFFIELD CHILDREN'S NHS FOUNDATION TRUST,MH & LD
TAH,SHEFFIELD HEALTH AND SOCIAL CARE NHS FOUNDATION TRUST,MH & LD
R1C,SOLENT NHS TRUST,MH & LD
RH5,SOMERSET PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RV5,SOUTH LONDON AND MAUDSLEY NHS FOUNDATION TRUST,MH & LD
RRE,SOUTH STAFFORDSHIRE AND SHROPSHIRE HEALTHCARE NHS FOUNDATION TRUST,MH & LD
RQY,SOUTH WEST LONDON AND ST GEORGE'S MENTAL HEALTH NHS TRUST,MH & LD
RXG,SOUTH WEST YORKSHIRE PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RW1,SOUTHERN HEALTH NHS FOUNDATION TRUST,MH & LD
RXX,SURREY AND BORDERS PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RX2,SUSSEX PARTNERSHIP NHS FOUNDATION TRUST,MH & LD
RX3,"TEES, ESK AND WEAR VALLEYS NHS FOUNDATION TRUST",MH & LD
RKL,WEST LONDON MENTAL HEALTH NHS TRUST,MH & LD
R1A,WORCESTERSHIRE HEALTH AND CARE NHS TRUST,MH & LD
REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,ACUTE
RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATION TRUST,ACUTE
R1H,BARTS HEALTH NHS TRUST,ACUTE
RYW,BIRMINGHAM COMMUNITY HEALTHCARE NHS TRUST,ACUTE
RQ3,BIRMINGHAM WOMEN'S AND CHILDREN'S NHS FOUNDATION TRUST,ACUTE
RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,ACUTE
RXH,BRIGHTON AND SUSSEX UNIVERSITY HOSPITALS NHS TRUST,ACUTE
RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,ACUTE
RW3,CENTRAL MANCHESTER UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,ACUTE
RQM,CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATION TRUST,ACUTE
RLN,CITY HOSPITALS SUNDERLAND NHS FOUNDATION TRUST,ACUTE
RJR,COUNTESS OF CHESTER HOSPITAL NHS FOUNDATION TRUST,ACUTE
RXP,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,ACUTE
RJN,EAST CHESHIRE NHS TRUST,ACUTE
RXC,EAST SUSSEX HEALTHCARE NHS TRUST,ACUTE
RDU,FRIMLEY HEALTH NHS FOUNDATION TRUST,ACUTE
RTE,GLOUCESTERSHIRE HOSPITALS NHS FOUNDATION TRUST,ACUTE
RN3,GREAT WESTERN HOSPITALS NHS FOUNDATION TRUST,ACUTE
RJ1,GUY'S AND ST THOMAS' NHS FOUNDATION TRUST,ACUTE
RCD,HARROGATE AND DISTRICT NHS FOUNDATION TRUST,ACUTE
RWA,HULL AND EAST YORKSHIRE HOSPITALS NHS FOUNDATION TRUST,ACUTE
RYJ,IMPERIAL COLLEGE HEALTHCARE NHS TRUST,ACUTE
RYY,KENT COMMUNITY HEALTH NHS FOUNDATION TRUST,ACUTE
RJZ,KING'S COLLEGE HOSPITAL NHS FOUNDATION TRUST,ACUTE
RAX,KINGSTON HOSPITAL NHS FOUNDATION TRUST,ACUTE
RXN,LANCASHIRE TEACHING HOSPITALS NHS FOUNDATION TRUST,ACUTE
RR8,LEEDS TEACHING HOSPITALS NHS TRUST,ACUTE
RJ2,LEWISHAM AND GREENWICH NHS TRUST,ACUTE
RM1,NORFOLK AND NORWICH UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,ACUTE
RVJ,NORTH BRISTOL NHS TRUST,ACUTE
RAP,NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST,ACUTE
RVW,NORTH TEES AND HARTLEPOOL NHS FOUNDATION TRUST,ACUTE
RNS,NORTHAMPTON GENERAL HOSPITAL NHS TRUST,ACUTE
RTH,OXFORD UNIVERSITY HOSPITALS NHS TRUST,ACUTE
RW6,PENNINE ACUTE HOSPITALS NHS TRUST,ACUTE
RK9,UNIVERSITY HOSPITALS PLYMOUTH HOSPITALS NHS TRUST,ACUTE
RHU,PORTSMOUTH HOSPITALS NHS TRUST,ACUTE
RHW,ROYAL BERKSHIRE NHS FOUNDATION TRUST,ACUTE
REF,ROYAL CORNWALL HOSPITALS NHS TRUST,ACUTE
RH8,ROYAL DEVON AND EXETER NHS FOUNDATION TRUST,ACUTE
RAL,ROYAL FREE LONDON NHS FOUNDATION TRUST,ACUTE
RQ6,ROYAL LIVERPOOL AND BROADGREEN UNIVERSITY HOSPITALS NHS TRUST,ACUTE
RAN,ROYAL NATIONAL ORTHOPAEDIC HOSPITAL NHS TRUST,ACUTE
RA2,ROYAL SURREY COUNTY HOSPITAL NHS FOUNDATION TRUST,ACUTE
RD1,ROYAL UNITED HOSPITALS BATH NHS FOUNDATION TRUST,ACUTE
RM3,SALFORD ROYAL NHS FOUNDATION TRUST,ACUTE
RNZ,SALISBURY NHS FOUNDATION TRUST,ACUTE
RTR,SOUTH TEES HOSPITALS NHS FOUNDATION TRUST,ACUTE
RVY,SOUTHPORT AND ORMSKIRK HOSPITAL NHS TRUST,ACUTE
RBA,TAUNTON AND SOMERSET NHS FOUNDATION TRUST,ACUTE
RNA,THE DUDLEY GROUP NHS FOUNDATION TRUST,ACUTE
RTD,THE NEWCASTLE UPON TYNE HOSPITALS NHS FOUNDATION TRUST,ACUTE
RCX,"THE QUEEN ELIZABETH HOSPITAL, KING'S LYNN, NHS FOUNDATION TRUST",ACUTE
RKE,THE WHITTINGTON HOSPITAL NHS TRUST,ACUTE
RA9,TORBAY AND SOUTH DEVON NHS FOUNDATION TRUST,ACUTE
RRV,UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDATION TRUST,ACUTE
RHM,UNIVERSITY HOSPITAL SOUTHAMPTON NHS FOUNDATION TRUST,ACUTE
RRK,UNIVERSITY HOSPITALS BIRMINGHAM NHS FOUNDATION TRUST,ACUTE
RA7,UNIVERSITY HOSPITALS BRISTOL NHS FOUNDATION TRUST,ACUTE
RKB,UNIVERSITY HOSPITALS COVENTRY AND WARWICKSHIRE NHS TRUST,ACUTE
RBK,WALSALL HEALTHCARE NHS TRUST,ACUTE
RWW,WARRINGTON AND HALTON HOSPITALS NHS FOUNDATION TRUST,ACUTE
RYR,WESTERN SUSSEX HOSPITALS NHS FOUNDATION TRUST,ACUTE
RA3,WESTON AREA HEALTH NHS TRUST,ACUTE
RBL,WIRRAL UNIVERSITY TEACHING HOSPITAL NHS FOUNDATION TRUST,ACUTE
RWP,WORCESTERSHIRE ACUTE HOSPITALS NHS TRUST,ACUTE
RA4,YEOVIL DISTRICT HOSPITAL NHS FOUNDATION TRUST,ACUTE
RCB,YORK TEACHING HOSPITAL NHS FOUNDATION TRUST,ACUTE
NVR,ALPHA HOSPITALS,INDEPENDENT
A7RH,ALTERNATIVE FUTURES GROUP LTD,INDEPENDENT
8JD96,BALDOCK MANOR,INDEPENDENT
8AM50,BILLINGHAM GRANGE,INDEPENDENT
8J554,BREIGHTMET CENTRE,INDEPENDENT
NQ9,BROOKDALE HEALTHCARE LTD (T/A BROOKDALE CARE),INDEPENDENT
DFL,CAMBIAN CHILDCARE LIMITED,INDEPENDENT
NT8,CAPIO UK,INDEPENDENT
NTP,CARE UK,INDEPENDENT
NTT,CAS BEHAVIOURAL HEALTH LIMITED,INDEPENDENT
8AP11,CASTLE LODGE INDEPENDENT HOSPITAL,INDEPENDENT
NDQ,CASTLEBECK CARE TEESDALE LTD,INDEPENDENT
NRN,CHESWOLD PARK HOSPITAL,INDEPENDENT
NAW,CHOICE LIFESTYLES LTD,INDEPENDENT
NHV,COMMUNITY LINKS (NORTHERN) LTD,INDEPENDENT
AHQ,CUROCARE LTD,INDEPENDENT
NMJ,CYGNET HEALTH CARE LIMITED,INDEPENDENT
AG0,DANSHELL GROUP,INDEPENDENT
NWA,ECHOTECH LTD,INDEPENDENT
8JC73,ELLERN MEDE RIDGEWAY,INDEPENDENT
DE8,ELYSIUM HEALTHCARE,INDEPENDENT
AHN,EQUILIBRIUM HEALTHCARE,INDEPENDENT
AHY,GLEN CARE,INDEPENDENT
NRY,HUNTERS MOOR NEUROREHABILITATION LTD,INDEPENDENT
AHL,INMIND HEALTHCARE,INDEPENDENT
NVJ,JEDHEATH LTD,INDEPENDENT
NLN,JEESAL AKMAN CARE CORPORATION LTD,INDEPENDENT
NL0,JOHN MUNROE HOSPITAL,INDEPENDENT
NES,LIGHTHOUSE HEALTHCARE LIMITED,INDEPENDENT
NR5,LIVEWELL SOUTHWEST,INDEPENDENT
NMQ,MAKING SPACE,INDEPENDENT
AJE,MENTAL HEALTH CARE  LTD,INDEPENDENT
NXQ,MODUS CARE,INDEPENDENT
NQL,NAVIGO,INDEPENDENT
ATM01,NEWBRIDGE CARE SYSTEMS,INDEPENDENT
NVH,NO 27 (BURNSIDE CARE),INDEPENDENT
AEXN,OPTIONS FOR CARE LTD,INDEPENDENT
NMV,PARTNERSHIPS IN CARE LTD,INDEPENDENT
NCP,PREMIER HEALTH & SPORT THERAPY LTD,INDEPENDENT
NTN,PRIORY GROUP LIMITED,INDEPENDENT
NR0,RAPHAEL HEALTHCARE LTD,INDEPENDENT
NRC,RIVERDALE GRANGE LIMITED,INDEPENDENT
ATM02,SCHOEN CLINIC YORK,INDEPENDENT
8CL59,SHREWSBURY COURT INDEPENDENT HOSPITAL,INDEPENDENT
NYA,ST ANDREW'S HEALTHCARE,INDEPENDENT
NQ4,ST GEORGE HEALTHCARE GROUP,INDEPENDENT
NR6,ST LUKES HEALTH CARE,INDEPENDENT
8CM63,ST MAGNUS HOSPITAL,INDEPENDENT
8K919,ST MARTHA'S,INDEPENDENT
NFJ,ST MATTHEWS LIMITED,INDEPENDENT
8DJ77,THE HAMPTONS,INDEPENDENT
NV2,THE HUNTERCOMBE GROUP,INDEPENDENT
NPE,THE RETREAT HOSPITAL,INDEPENDENT
NKD,THE YOUTH ENQUIRY SERVICE (PLYMOUTH) LTD,INDEPENDENT
NLH,TRANSITIONAL REHABILITATION UNIT (TRU),INDEPENDENT
NKI,TURNING POINT,INDEPENDENT
8G046,UPLANDS,INDEPENDENT
8J339,VISION MENTAL HEALTHCARE,INDEPENDENT
8CJ54,WOODLEIGH COMMUNITY INDEPENDENT HOSPITAL,INDEPENDENT
NR1,WOODSIDE HOSPITAL,INDEPENDENT
AD918,UTC - CENTRAL MIDDLESEX HOSPITAL,INDEPENDENT
DWW,ACTIVE PATHWAYS,INDEPENDENT
NQT5G,URGENT CARE CENTRE,INDEPENDENT
NTPAN,PRACTICE PLUS GROUP URGENT TREATMENT CENTRE - SOUTHAMPTON,INDEPENDENT
RCF,AIREDALE NHS FOUNDATION TRUST,ACUTE
RGR,WEST SUFFOLK NHS FOUNDATION TRUST,ACUTE
RJ7,ST GEORGE'S UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,ACUTE
RJC,SOUTH WARWICKSHIRE NHS FOUNDATION TRUST,ACUTE
RNN,NORTH CUMBRIA INTEGRATED CARE NHS FOUNDATION TRUST,ACUTE
RP5,DONCASTER AND BASSETLAW TEACHING HOSPITALS NHS FOUNDATION TRUST,ACUTE
RQW,THE PRINCESS ALEXANDRA HOSPITAL NHS TRUST,ACUTE
RQX,HOMERTON HEALTHCARE NHS FOUNDATION TRUST,ACUTE
RVV,EAST KENT HOSPITALS UNIVERSITY NHS FOUNDATION TRUST,ACUTE
RWF,MAIDSTONE AND TUNBRIDGE WELLS NHS TRUST,ACUTE
RXL,BLACKPOOL TEACHING HOSPITALS NHS FOUNDATION TRUST,ACUTE
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.org_type")

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_1a_history;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_1a_history
 ---dq table 1a containing historic dq figures
 (
 Org_Type string,
 T1a_2015_16 int,
 T1a_2016_17 int,
 T1a_2017_18 int,
 T1a_2018_19 int,
 T1a_2019_20 int,
 T1a_2020_21 int
 )

# COMMAND ----------

#raw data for dq table 1a containing historic dq figures to be inserted into $db_output.dq_table_1a_history
data = """
Org_Type,T1a_2015_16,T1a2016_17,T1a_2017_18,T1a_2018_19,T1a_2019_20,T1a_2020_21
All organisations,172,128,126,103,104,108
NHS Providers,126,114,111,86,85,91
Mental Health and Learning Disabilities Trusts,63,60,60,60,60,60
Acute Trusts,63,54,51,26,25,31
Independent Providers,46,12,15,17,19,17
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.dq_table_1a_history")

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_1b_history;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_1b_history
 ---dq table 1b containing historic dq figures
 (
 Org_Type string,
 T1b_2015_16 int,
 T1b_2016_17 int,
 T1b_2017_18 int,
 T1b_2018_19 int,
 T1b_2019_20 int,
 T1b_2020_21 int
 )

# COMMAND ----------

#raw data for dq table 1b containing historic dq figures to be inserted into $db_output.dq_table_1b_history
data = """
Org_Type,T1a_2015_16,T1a2016_17,T1a_2017_18,T1a_2018_19,T1a_2019_20,T1a_2020_21
All organisations,63622,45864,49551,49988,50893,53239
NHS Providers,56594,43050,46552,46837,47975,50518
Mental Health and Learning Disabilities Trusts,54921,41268,44206,45717,46738,49038
Acute Trusts,1673,1782,2346,1120,1237,1480
Independent Providers,7028,2814,2999,3151,2918,2721
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.dq_table_1b_history")

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_prov_type_subm_detentions_year;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_prov_type_subm_detentions_year AS
 ---final prep table for number of providers submitting mha data and detentions by organisation type (nhs mental health and learning disabilities trust or nhs acute trust or independent provider)
 select
 replace("$year", "/", "-") as year,
 ORG_TYPE as org_type,
 count(distinct OrgID) as providers,
 sum(Total_Count) as detentions
 from (select distinct OrganisationBreakdown, OrgID, Total_Count from $db_output.mha_raw where OrganisationBreakdown in ("NHS TRUST", "INDEPENDENT HEALTH PROVIDER") and OrgID <> "All prov" and Measure = "All detentions") org
 left join $db_output.org_type ot on org.OrgID = ot.ORG_CODE
 group by 
 replace("$year", "/", "-"),
 ORG_TYPE

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_prov_type_subm_year;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_prov_type_subm_year AS
 ---final table for number of providers submitting mha data by organisation type (nhs mental health and learning disabilities trust or nhs acute trust or independent provider)
 select
 'All organisations' as Org_Type,
 sum(providers) as providers
 from $db_output.dq_mha_prov_type_subm_detentions_year
 union
 select
 'NHS Providers' as Org_Type,
 sum(providers) as providers
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type in ("MH & LD", "ACUTE")
 union
 select
 case when org_type = "MH & LD" then "Mental Health and Learning Disabilities Trusts"
      when org_type = "ACUTE" then "Acute Trusts" end Org_Type,
 sum(providers) as providers
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type in ("MH & LD", "ACUTE")
 group by case when org_type = "MH & LD" then "Mental Health and Learning Disabilities Trusts"
      when org_type = "ACUTE" then "Acute Trusts" end
 union
 select
 'Independent Providers' as Org_Type,
 sum(providers) as providers
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type = "INDEPENDENT"

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_prov_type_det_year;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_prov_type_det_year AS
 ---final table for number of detentions by organisation type (nhs mental health and learning disabilities trust or nhs acute trust or independent provider)
 select
 'All organisations' as Org_Type,
 sum(detentions) as detentions
 from $db_output.dq_mha_prov_type_subm_detentions_year
 union
 select
 'NHS Providers' as Org_Type,
 sum(detentions) as detentions
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type in ("MH & LD", "ACUTE")
 union
 select
 case when org_type = "MH & LD" then "Mental Health and Learning Disabilities Trusts"
      when org_type = "ACUTE" then "Acute Trusts" end as Org_Type,
 sum(detentions) as detentions
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type in ("MH & LD", "ACUTE")
 group by case when org_type = "MH & LD" then "Mental Health and Learning Disabilities Trusts"
      when org_type = "ACUTE" then "Acute Trusts" end
 union
 select
 'Independent Providers' as Org_Type,
 sum(detentions) as detentions
 from $db_output.dq_mha_prov_type_subm_detentions_year
 where org_type = "INDEPENDENT"

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_submissions_12m;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_submissions_12m AS
 ---providers submitting to MHS000Header and MHS401MHActPeriod tables in the financial year
 SELECT 
 DISTINCT 
 A.OrgIDProvider,
 NAME,
 ORG_TYPE_CODE,
 COUNT(DISTINCT A.UniqMonthID) AS TOTAL_SUBMISSIONS,
 COUNT(DISTINCT C.UniqMonthID) AS MHA_SUBMISSIONS
 FROM 
 $db_source.mhs000header A
 LEFT JOIN $db_output.mha_rd_org_daily_latest B ON A.OrgIDProvider = B.ORG_CODE
 LEFT JOIN $db_output.mhs401_latest C ON A.OrgIDProvider = C.OrgIDProv AND A.UniqMonthID = C.UniqMonthID AND C.UniqMonthID BETWEEN $start_month_id AND $month_id
 WHERE
 A.UniqMonthID BETWEEN $start_month_id AND $month_id
 --AND NAME IS NULL
 GROUP BY 
 OrgIDProvider,
 NAME,
 ORG_TYPE_CODE

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_prov_submissions_org_type;
 CREATE TABLE IF NOT EXISTS $db_output.dq_prov_submissions_org_type AS
 ---total number of providers submitting to MHS401MHActPeriod Table in the financial year by organisation type (NHS Trust or Independent Provider)
 SELECT 
 A.UniqMonthID,
 C.ReportingPeriodStartDate,
 COUNT(DISTINCT A.OrgIDProv) as Providers_submitting,
 COUNT(DISTINCT CASE WHEN ORG_TYPE_CODE = 'NHS TRUST' THEN A.OrgIDProv ELSE NULL END) AS NHS_SUBMITTING,
 COUNT(DISTINCT CASE WHEN ORG_TYPE_CODE = 'INDEPENDENT HEALTH PROVIDER' THEN A.OrgIDProv ELSE NULL END) AS IND_SUBMITTING
 FROM 
 $db_output.mhs401_latest A 
 LEFT JOIN $db_output.mha_rd_org_daily_latest B ON A.OrgIDProv = B.ORG_CODE
 LEFT JOIN (SELECT 
             DISTINCT 
             UniqMonthID, 
             ReportingPeriodStartDate
             FROM 
             $db_source.mhs000header
             WHERE
             UniqMonthID BETWEEN $start_month_id AND $month_id)
             AS C
             ON C.UniqMonthID = A.UniqMonthID
 WHERE
 A.UniqMonthID BETWEEN $start_month_id AND $month_id
 GROUP BY 
 A.UniqMonthID,
 C.ReportingPeriodStartDate
 ORDER BY 1 ASC

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_3_prep;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_3_prep AS
 ---prep table for mha dq table 3 stage 1
 SELECT
 UniqMHActEpisodeID,
 OrgIDProv,
 case when (length(OrgIDProv) = 3 and left(OrgIDProv, 1) in ("R", "T")) then "NHS"
      else "Independent" end as OrgType,
 CASE 
 WHEN AgeRepPeriodEnd between 0 and 15 then '15 and under'
 WHEN AgeRepPeriodEnd between 16 and 17 then '16 to 17'
 WHEN AgeRepPeriodEnd between 18 and 34 then '18 to 34'
 WHEN AgeRepPeriodEnd between 35 and 49 then '35 to 49'
 WHEN AgeRepPeriodEnd between 50 and 64 then '50 to 64'
 WHEN AgeRepPeriodEnd >= 65 then '65 and over' 
 END as Age,
 CASE
 WHEN EthnicCategory IN ('A','B','C') THEN 'White'
 WHEN EthnicCategory IN ('D','E','F','G') THEN 'Mixed'
 WHEN EthnicCategory IN ('H','J','K','L') THEN 'Asian or Asian British'
 WHEN EthnicCategory IN ('M','N','P') THEN 'Black or Black British'
 WHEN EthnicCategory IN ('R','S') THEN 'Other Ethnic Groups'
 ELSE 'Unknown'
 END as Upper_Eth,
 case when Der_Gender = '1' then 'Male'
      when Der_Gender = '2' then 'Female'
      when Der_Gender = '3' then 'Non-binary'
      when Der_Gender = '4' then 'Other (not listed)'
      when Der_Gender = '9' then 'Indeterminate'
      else 'Unknown' end as Der_Gender
 from $db_output.detentions
 where
 MHA_Logic_Cat_full in ('A','B','C','D','P')

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_3_prep2;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_3_prep2 AS
 ---prep table for mha dq table 3 stage 2
 select
 coalesce(OrgType, "All") as OrgType,
 coalesce(Age, "All") as Age,
 coalesce(Upper_Eth, "All") as Upper_Eth,
 coalesce(Der_Gender, "All") as Der_Gender,
 count(distinct UniqMHActEpisodeID) as detentions
 from $db_output.dq_table_3_prep
 group by 
 grouping sets
 (
 (Age),
 (Upper_Eth),
 (Der_Gender),
 (OrgType, Age),
 (OrgType, Upper_Eth),
 (OrgType, Der_Gender)
 )

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_3_prep3;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_3_prep3 AS
 ---prep table for mha dq table 3 stage 3
 select 
 "All" as OrgType,
 "Gender" as breakdown,
 Der_Gender as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Der_Gender <> "All" and OrgType = "All"
 union 
 select
 "All" as OrgType,
 "Age" as breakdown,
 Age as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Age <> "All" and OrgType = "All"
 union 
 select
 "All" as OrgType,
 "Ethnicity" as breakdown,
 Upper_Eth as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Upper_Eth <> "All" and OrgType = "All"
 union
 select 
 OrgType as OrgType,
 "Gender" as breakdown,
 Der_Gender as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Der_Gender <> "All" and OrgType <> "All"
 union
 select
 OrgType as OrgType,
 "Age" as breakdown,
 Age as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Age <> "All" and OrgType <> "All"
 union 
 select
 OrgType as OrgType,
 "Ethnicity" as breakdown,
 Upper_Eth as level,
 detentions
 from $db_output.dq_table_3_prep2
 where Upper_Eth <> "All" and OrgType <> "All"

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_time;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_time AS
 ---prep table for mha dq table 5 time recording for detention start time
 SELECT 
 case when minute(StartTimeMHActLegalStatusClass) = 0 then "On the hour"
      when minute(StartTimeMHActLegalStatusClass) in (15, 45) then "Quarter past and quarter to the hour"
      when minute(StartTimeMHActLegalStatusClass) = 30 then "On the half hour"
      else "All other times" end as time_recording,
 COUNT(DISTINCT UniqMHActEpisodeID) as count
 FROM
 $db_output.detentions
 WHERE
 MHA_Logic_Cat_full in ('A','B','C','D','P')
 GROUP BY 
 case when minute(StartTimeMHActLegalStatusClass) = 0 then "On the hour"
      when minute(StartTimeMHActLegalStatusClass) in (15, 45) then "Quarter past and quarter to the hour"
      when minute(StartTimeMHActLegalStatusClass) = 30 then "On the half hour"
      else "All other times" end

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_hospital_time;
 CREATE TABLE IF NOT EXISTS $db_output.dq_hospital_time AS
 ---prep table for mha dq table 5 time recording for hospital spell start time
 SELECT 
 case when minute(StartTimeHospProvSpell) = 0 then "On the hour"
      when minute(StartTimeHospProvSpell) in (15, 45) then "Quarter past and quarter to the hour"
      when minute(StartTimeHospProvSpell) = 30 then "On the half hour"
      else "All other times" end as time_recording,
 COUNT(DISTINCT UniqMHActEpisodeID) as count
 FROM
 $db_output.detentions
 WHERE
 MHA_Logic_Cat_full in ('A','B','C','D','P')
 GROUP BY 
 case when minute(StartTimeHospProvSpell) = 0 then "On the hour"
      when minute(StartTimeHospProvSpell) in (15, 45) then "Quarter past and quarter to the hour"
      when minute(StartTimeHospProvSpell) = 30 then "On the half hour"
      else "All other times" end

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_mha_time_recording;
 CREATE TABLE IF NOT EXISTS $db_output.dq_mha_time_recording AS
 ---prep table for mha dq table 5 time recording for both detention and hospital spell start time
 select
 mha.time_recording,
 mha.count as MHA_Count,
 hosp.count as Hosp_Count
 from $db_output.dq_mha_time mha
 left join $db_output.dq_hospital_time hosp on mha.time_recording = hosp.time_recording

# COMMAND ----------

# DBTITLE 0,DQ Table 6 History
 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_6_history;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_6_history
 ---dq table 6 containing historic dq figures
 (
 Detention_Type string,
 T6_2017_18 int,
 T6_2018_19 int,
 T6_2019_20 int,
 T6_2020_21 int
 )

# COMMAND ----------

#raw data for dq table 6 containing historic dq figures to be inserted into $db_output.dq_table_6_history
data = """
Detention_Type,T6_2017_18,T6_2018_19,T6_2019_20,T6_2020_21
All Detentions,22535,23365,23555,24604
Detentions on admission to hospital,14228,15596,16174,17370
Detentions following admission to hospital,6853,6012,5474,5119
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.dq_table_6_history")

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_6_year;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_6_year
 ---get counts of detentions for 24 selected provider for financial year (to be joined to dq table 6 history later)
 select 
 "All Detentions" as Detention_Type, count(distinct UniqMHActEpisodeID) as count
 from $db_output.detentions
 where OrgIDProv IN ("NR5", "RTQ", "RVN", "RRP", "RXT", "TAD", "TAF", "RJ8", "RXM", "RMV", "RWK", "RV9", "RP7", "RMY", "RX4", "RHA", "TAH", "RRE", "RQY", "RW1", "RX2", "RX3", "RKL", "R1A", "RWV")
 and MHA_Logic_Cat_full in ('A','B','C','D','P')
 UNION
 select 
 "Detentions on admission to hospital" as Detention_Type, count(distinct UniqMHActEpisodeID) as count
 from $db_output.detentions
 where OrgIDProv IN ("NR5", "RTQ", "RVN", "RRP", "RXT", "TAD", "TAF", "RJ8", "RXM", "RMV", "RWK", "RV9", "RP7", "RMY", "RX4", "RHA", "TAH", "RRE", "RQY", "RW1", "RX2", "RX3", "RKL", "R1A", "RWV")
 and MHA_Logic_Cat_full in ('A','P')
 UNION
 select 
 "Detentions following admission to hospital" as Detention_Type, count(distinct UniqMHActEpisodeID) as count
 from $db_output.detentions
 where OrgIDProv IN ("NR5", "RTQ", "RVN", "RRP", "RXT", "TAD", "TAF", "RJ8", "RXM", "RMV", "RWK", "RV9", "RP7", "RMY", "RX4", "RHA", "TAH", "RRE", "RQY", "RW1", "RX2", "RX3", "RKL", "R1A", "RWV")
 and MHA_Logic_Cat_full in ('B')

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_kp90_submitters;
 CREATE TABLE IF NOT EXISTS $db_output.dq_kp90_submitters
 ---dq table 7 containing historic dq figures for submissions to kp90
 (
 Org_Code string,
 Org_Name string,
 Detentions string
 )

# COMMAND ----------

#raw data for dq table 7 containing historic dq figures for submissions to kp90 to be inserted into $db_output.dq_kp90_submitters
data = """
Org_Code,Org_Name, Detentions
RTQ,2GETHER NHS FOUNDATION TRUST,670
RTV,5 BOROUGHS PARTNERSHIP NHS FOUNDATION TRUST,990
A7RH,ALTERNATIVE FUTURES GROUP LTD,35
RTK,ASHFORD AND ST PETER'S HOSPITALS NHS FOUNDATION TRUST,10
RVN,AVON AND WILTSHIRE MENTAL HEALTH PARTNERSHIP NHS TRUST,1640
8JD96,BALDOCK MANOR,*
KP9097,BARCHESTER HEALTHCARE HOMES LIMITED,*
RRP,"BARNET, ENFIELD AND HARINGEY MENTAL HEALTH NHS TRUST",1095
R1H,BARTS HEALTH NHS TRUST,55
RWX,BERKSHIRE HEALTHCARE NHS FOUNDATION TRUST,590
8AM50,BILLINGHAM GRANGE,10
RXT,BIRMINGHAM AND SOLIHULL MENTAL HEALTH NHS FOUNDATION TRUST,1445
RQ3,BIRMINGHAM CHILDREN'S HOSPITAL NHS FOUNDATION TRUST,30
RYW,BIRMINGHAM COMMUNITY HEALTHCARE NHS TRUST,*
TAJ,BLACK COUNTRY PARTNERSHIP NHS FOUNDATION TRUST,545
TAD,BRADFORD DISTRICT CARE TRUST,655
RAE,BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST,45
8J554,BREIGHTMET CENTRE,5
RXH,BRIGHTON AND SUSSEX UNIVERSITY HOSPITALS NHS TRUST,25
NQ9,BROOKDALE HEALTHCARE LTD (T/A BROOKDALE CARE),20
RJF,BURTON HOSPITALS NHS FOUNDATION TRUST,10
RJX,CALDERSTONES PARTNERSHIP NHS FOUNDATION TRUST,10
NTT,CAMBIAN HEALTHCARE LIMITED (now called CAS BEHAVIOURAL HEALTH LIMITED),275
RGT,CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,45
RT1,CAMBRIDGESHIRE AND PETERBOROUGH NHS FOUNDATION TRUST,530
TAF,CAMDEN AND ISLINGTON NHS FOUNDATION TRUST,935
NT8,CAPIO UK,90
8AP11,CASTLE LODGE INDEPENDENT HOSPITAL,5
RV3,CENTRAL AND NORTH WEST LONDON NHS FOUNDATION TRUST,3085
RW3,CENTRAL MANCHESTER UNIVERSITY HOSPITALS NHS FOUNDATION TRUST,*
RQM,CHELSEA AND WESTMINSTER HOSPITAL NHS FOUNDATION TRUST,15
RXA,CHESHIRE AND WIRRAL PARTNERSHIP NHS FOUNDATION TRUST,920
NRN,CHESWOLD PARK HOSPITAL,20
RLN,CITY HOSPITALS SUNDERLAND NHS FOUNDATION TRUST,10
RJ8,CORNWALL PARTNERSHIP NHS FOUNDATION TRUST,280
RXP,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,10
RYG,COVENTRY AND WARWICKSHIRE PARTNERSHIP NHS TRUST,795
RNN,CUMBRIA PARTNERSHIP NHS FOUNDATION TRUST,545
AHQ,CUROCARE LTD,30
NMJ,CYGNET HEALTH CARE LIMITED,1915
AG0,DANSHELL GROUP,45
RTG,DERBY TEACHING HOSPITALS NHS FOUNDATION TRUST,5
RY8,DERBYSHIRE COMMUNITY HEALTH SERVICES NHS FOUNDATION TRUST,90
RXM,DERBYSHIRE HEALTHCARE NHS FOUNDATION TRUST,785
RWV,DEVON PARTNERSHIP NHS TRUST,985
RDY,DORSET HEALTHCARE UNIVERSITY NHS FOUNDATION TRUST,680
RYK,DUDLEY AND WALSALL MENTAL HEALTH PARTNERSHIP NHS TRUST,335
RWK,EAST LONDON NHS FOUNDATION TRUST,2205
RXC,EAST SUSSEX HEALTHCARE NHS TRUST,20
8JC73,ELLERN MEDE RIDGEWAY,5
AHN,EQUILIBRIUM HEALTHCARE,10
RDU,FRIMLEY HEALTH NHS FOUNDATION TRUST,5
RR7,GATESHEAD HEALTH NHS FOUNDATION TRUST,65
AHY,GLEN CARE,10
RTE,GLOUCESTERSHIRE HOSPITALS NHS FOUNDATION TRUST,*
RN3,GREAT WESTERN HOSPITALS NHS FOUNDATION TRUST,20
RXV,GREATER MANCHESTER WEST MENTAL HEALTH NHS FOUNDATION TRUST,735
RJ1,GUY'S AND ST THOMAS' NHS FOUNDATION TRUST,90
RN5,HAMPSHIRE HOSPITALS NHS FOUNDATION TRUST,10
RCD,HARROGATE AND DISTRICT NHS FOUNDATION TRUST,*
RWR,HERTFORDSHIRE PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST,900
RV9,HUMBER NHS FOUNDATION TRUST,480
NRY,HUNTERS MOOR NEUROREHABILITATION LTD,5
RYJ,IMPERIAL COLLEGE HEALTHCARE NHS TRUST,40
AHL,INMIND HEALTHCARE,20
R1F,ISLE OF WIGHT NHS TRUST,155
NLN,JEESAL AKMAN CARE CORPORATION LTD,25
NL0,JOHN MUNROE HOSPITAL,25
RXY,KENT AND MEDWAY NHS AND SOCIAL CARE PARTNERSHIP TRUST,1265
RJZ,KING'S COLLEGE HOSPITAL NHS FOUNDATION TRUST,75
RAX,KINGSTON HOSPITAL NHS FOUNDATION TRUST,35
RW5,LANCASHIRE CARE NHS FOUNDATION TRUST,1550
RGD,LEEDS AND YORK PARTNERSHIP NHS FOUNDATION TRUST,1125
RY6,LEEDS COMMUNITY HEALTHCARE NHS TRUST,15
RR8,LEEDS TEACHING HOSPITALS NHS TRUST,85
RT5,LEICESTERSHIRE PARTNERSHIP NHS TRUST,835
NES,LIGHTHOUSE HEALTHCARE LIMITED,30
RP7,LINCOLNSHIRE PARTNERSHIP NHS FOUNDATION TRUST,410
NMQ,MAKING SPACE,15
TAE,MANCHESTER MENTAL HEALTH AND SOCIAL CARE TRUST,1015
AJE,MENTAL HEALTH CARE  LTD,10
RW4,MERSEY CARE NHS TRUST,830
RD8,MILTON KEYNES UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,*
NQL,NAVIGO,175
RMY,NORFOLK AND SUFFOLK NHS FOUNDATION TRUST,1125
RVJ,NORTH BRISTOL NHS TRUST,20
RAT,NORTH EAST LONDON NHS FOUNDATION TRUST,850
RRD,NORTH ESSEX PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST,840
RAP,NORTH MIDDLESEX UNIVERSITY HOSPITAL NHS TRUST,190
RLY,NORTH STAFFORDSHIRE COMBINED HEALTHCARE NHS TRUST,480
RVW,NORTH TEES AND HARTLEPOOL NHS FOUNDATION TRUST,*
RV8,NORTH WEST LONDON HOSPITALS NHS TRUST,15 
RP1,NORTHAMPTONSHIRE HEALTHCARE NHS FOUNDATION TRUST,420
RX4,"NORTHUMBERLAND, TYNE AND WEAR NHS FOUNDATION TRUST",1665
RTF,NORTHUMBRIA HEALTHCARE NHS FOUNDATION TRUST,70
RHA,NOTTINGHAMSHIRE HEALTHCARE NHS FOUNDATION TRUST,1125
AEXN,OPTIONS FOR CARE LTD,*
RNU,OXFORD HEALTH NHS FOUNDATION TRUST,1070
RTH,OXFORD UNIVERSITY HOSPITALS NHS TRUST,10
RPG,OXLEAS NHS FOUNDATION TRUST,990
NMV,PARTNERSHIPS IN CARE LTD,335
RT2,PENNINE CARE NHS FOUNDATION TRUST,1270
NR5,PLYMOUTH COMMUNITY HEALTHCARE (CIC) (now called LIVEWELL SOUTHWEST),265
RK9,PLYMOUTH HOSPITALS NHS TRUST,20
RD3,POOLE HOSPITAL NHS FOUNDATION TRUST,45
RHU,PORTSMOUTH HOSPITALS NHS TRUST,80
NTN,PRIORY GROUP LIMITED,2140
NR0,RAPHAEL HEALTHCARE LTD,15
RXE,ROTHERHAM DONCASTER AND SOUTH HUMBER NHS FOUNDATION TRUST,830
RHW,ROYAL BERKSHIRE NHS FOUNDATION TRUST,10
REF,ROYAL CORNWALL HOSPITALS NHS TRUST,45
RH8,ROYAL DEVON AND EXETER NHS FOUNDATION TRUST,55
RAL,ROYAL FREE HAMPSTEAD NHS TRUST,65
RA2,ROYAL SURREY COUNTY HOSPITAL NHS FOUNDATION TRUST,5
RD1,ROYAL UNITED HOSPITALS BATH NHS FOUNDATION TRUST,5
RM3,SALFORD ROYAL NHS FOUNDATION TRUST,*
RNZ,SALISBURY NHS FOUNDATION TRUST,5
RCU,SHEFFIELD CHILDREN'S NHS FOUNDATION TRUST,5
TAH,SHEFFIELD HEALTH AND SOCIAL CARE NHS FOUNDATION TRUST,605
8CL59,SHREWSBURY COURT INDEPENDENT HOSPITAL,*
R1C,SOLENT NHS TRUST,240
RH5,SOMERSET PARTNERSHIP NHS FOUNDATION TRUST,445
RA9,SOUTH DEVON HEALTHCARE NHS FOUNDATION TRUST,10
RWN,SOUTH ESSEX PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST,600
RV5,SOUTH LONDON AND MAUDSLEY NHS FOUNDATION TRUST,2170
RRE,SOUTH STAFFORDSHIRE AND SHROPSHIRE HEALTHCARE NHS FOUNDATION TRUST,975
RTR,SOUTH TEES HOSPITALS NHS FOUNDATION TRUST,10
RQY,SOUTH WEST LONDON AND ST GEORGE'S MENTAL HEALTH NHS TRUST,1475
RXG,SOUTH WEST YORKSHIRE PARTNERSHIP NHS FOUNDATION TRUST,1105
RW1,SOUTHERN HEALTH NHS FOUNDATION TRUST,1245
RVY,SOUTHPORT AND ORMSKIRK HOSPITAL NHS TRUST,5
NYA,ST ANDREW'S HEALTHCARE,785
NQ4,ST GEORGE HEALTHCARE GROUP,15
8CM63,ST MAGNUS HOSPITAL,35
NFJ,ST MATTHEWS LIMITED,15
RXX,SURREY AND BORDERS PARTNERSHIP NHS FOUNDATION TRUST,610
RX2,SUSSEX PARTNERSHIP NHS FOUNDATION TRUST,1770
RMP,TAMESIDE HOSPITAL NHS FOUNDATION TRUST,10
RBA,TAUNTON AND SOMERSET NHS FOUNDATION TRUST,5
RX3,"TEES, ESK AND WEAR VALLEYS NHS FOUNDATION TRUST",2175
8J704,THE ATARRAH PROJECT LTD,*
RNA,THE DUDLEY GROUP NHS FOUNDATION TRUST,10
8DJ77,THE HAMPTONS,5
NV2,THE HUNTERCOMBE GROUP,440
RTD,THE NEWCASTLE UPON TYNE HOSPITALS NHS FOUNDATION TRUST,15
RCX,"THE QUEEN ELIZABETH HOSPITAL, KING'S LYNN, NHS FOUNDATION TRUST",15
8GG74,THE RETREAT (YORK HOUSE),10
NPE,THE RETREAT HOSPITAL GROUP,15
RKE,THE WHITTINGTON HOSPITAL NHS TRUST,200
NLH,TRANSITIONAL REHABILITATION UNIT (TRU),*
NKI,TURNING POINT,10
RRV,UNIVERSITY COLLEGE LONDON HOSPITALS NHS FOUNDATION TRUST,15
RHM,UNIVERSITY HOSPITAL SOUTHAMPTON NHS FOUNDATION TRUST,55
RRK,UNIVERSITY HOSPITALS BIRMINGHAM NHS FOUNDATION TRUST,30
RKB,UNIVERSITY HOSPITALS COVENTRY AND WARWICKSHIRE NHS TRUST,40
8G046,UPLANDS (FAREHAM),5
8J339,VISION MENTAL HEALTHCARE,10
RWW,WARRINGTON AND HALTON HOSPITALS NHS FOUNDATION TRUST,*
RKL,WEST LONDON MENTAL HEALTH NHS TRUST,1175
RYR,WESTERN SUSSEX HOSPITALS NHS FOUNDATION TRUST,5
RA3,WESTON AREA HEALTH NHS TRUST,*
8CJ54,WOODLEIGH COMMUNITY INDEPENDENT HOSPITAL,5
NR1,WOODSIDE HOSPITAL,5
RWP,WORCESTERSHIRE ACUTE HOSPITALS NHS TRUST,5
R1A,WORCESTERSHIRE HEALTH AND CARE NHS TRUST,370
RA4,YEOVIL DISTRICT HOSPITAL NHS FOUNDATION TRUST,5
RCB,YORK TEACHING HOSPITAL NHS FOUNDATION TRUST,25
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.dq_kp90_submitters")

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.dq_table_10_history;
 CREATE TABLE IF NOT EXISTS $db_output.dq_table_10_history
 ---dq table 10 containing historic dq figures
 (
 Org_Code string,
 Org_Type string,
 T5_2015_16 string,
 T5_2016_17 string,
 T5_2017_18 string,
 T5_2018_19 string,
 T5_2019_20 string,
 T5_2020_21 string
 )

# COMMAND ----------

#raw data for dq table 10 containing historic dq figures to be inserted into $db_output.dq_table_10_history
data = """
Org_Code,Org_Type,T5_2015_16,T52016_17,T5_2017_18,T5_2018_19,T5_2019_20,T5_2020_21
NR5,Independent,80,75,60,80,65,70
R1A,MH,90,95,100,120,115,145
RHA,MH,855,795,765,755,635,670
RJ8,MH,105,125,105,100,115,125
RKL,MH,775,740,785,770,720,760
RMY,MH,335,355,370,370,345,375
RP7,MH,130,130,145,110,110,100
RQY,MH,420,395,430,395,400,420
RRE,MH,310,245,230,200,205,235
RRP,MH,440,505,510,560,560,580
RTQ,MH,180,215,210,220,195,175
RV9,MH,195,200,205,175,170,190
RVN,MH,510,475,500,520,485,510
RW1,MH,355,435,430,425,390,265
RWK,MH,790,725,805,805,685,690
RWV,MH,285,150,145,160,135,140
RX2,MH,515,255,395,410,435,460
RX3,MH,895,690,715,650,635,640
RX4,MH,750,685,705,650,745,695
RXM,MH,225,220,230,235,230,200
RXT,MH,705,765,805,860,860,910
TAD,MH,200,200,220,180,175,155
TAF,MH,285,410,400,420,395,400
TAH,MH,200,200,210,210,220,210
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.dq_table_10_history")

# COMMAND ----------

 %sql
 REFRESH TABLE $db_output.mha_mhs08_dq_prep;
 DROP TABLE IF EXISTS $db_output.mha_dq_table10_year;
 CREATE TABLE IF NOT EXISTS $db_output.mha_dq_table10_year AS
 ---gets people subject to the act for the 24 selected providers for March of the financial year
 select OrgIDProv,
 suppress(count(distinct person_id)) as mhs08
 from $db_output.mha_mhs08_prep
 where OrgIDProv IN ("NR5", "RTQ", "RVN", "RRP", "RXT", "TAD", "TAF", "RJ8", "RXM", "RMV", "RWK", "RV9", "RP7", "RMY", "RX4", "RHA", "TAH", "RRE", "RQY", "RW1", "RX2", "RX3", "RKL", "R1A", "RWV")
 group by OrgIDProv

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.pbi_dq_table_2_history;
 CREATE TABLE IF NOT EXISTS $db_output.pbi_dq_table_2_history
 ---power bi dq table 2 containing historic dq figures
 (
 Org_Code string,
 Org_Type string,
 T2_2015_16 string,
 T2_2016_17 string,
 T2_2017_18 string,
 T2_2018_19 string,
 T2_2019_20 string,
 T2_2020_21 string,
 MHA_MONTHS_2016_17 int,
 MHA_MONTHS_2017_18 int,
 MHA_MONTHS_2018_19 int,
 MHA_MONTHS_2019_20 int,
 MHA_MONTHS_2020_21 int
 )

# COMMAND ----------

#raw data for power bi dq table 2 containing historic dq figures to be inserted into $db_output.pbi_dq_table_2_history
data = """Org_Code,OrgType,T2_2015_16,T2_2016_17,T2_2017_18,T2_2018_19,T2_2019_20,T2_2020_21,MHA_MONTHS_2016_17,MHA_MONTHS_2017_18,MHA_MONTHS_2018_19,MHA_MONTHS_2019_20,MHA_MONTHS_2020_21
8CM63,Independent,KP90,None,None,None,MHSDS,MHSDS,0,0,0,11,12
8K919,Independent,None,None,None,None,MHSDS,MHSDS,0,0,0,4,12
AHL,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,10,12,12
AHN,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,6,12,12,12,12
DE8,Independent,None,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,4,12,12,12,12
DFL,Independent,None,None,MHSDS,MHSDS,MHSDS,None,0,11,12,8,0
NFJ,Independent,KP90,None,None,MHSDS,MHSDS,MHSDS,0,0,0,8,12
NHV,Independent,None,MHSDS,MHSDS,MHSDS,None,None,12,12,12,0,0
NKD,Independent,None,None,MHSDS,MHSDS,MHSDS,MHSDS,0,11,12,11,0
NKI,Independent,KP90,None,None,None,MHSDS,MHSDS,0,0,0,8,5
NL0,Independent,KP90,None,None,None,MHSDS,MHSDS,0,0,0,6,12
NLN,Independent,KP90,None,MHSDS,MHSDS,MHSDS,MHSDS,0,6,12,12,9
NMJ,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,11,12,12
NMQ,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,10,10,12,12,12
NMV,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,8,0,4,0,0
NQ4,Independent,KP90,MHSDS,MHSDS,MHSDS,None,None,9,11,3,0,0
NQL,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
NR0,Independent,KP90,MHSDS,None,None,None,None,9,0,0,0,0
NR5,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
NRC,Independent,None,None,None,None,MHSDS,MHSDS,0,0,0,12,12
NRN,Independent,KP90,None,None,None,MHSDS,MHSDS,0,0,0,10,12
NTN,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,8,4,4,0,0
NTT,Independent,KP90,MHSDS,MHSDS,MHSDS,None,None,12,12,7,0,0
NV2,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,0,4,12,12,12
NYA,Independent,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,9,12,12,12,12
R0A,NHS,None,None,MHSDS,MHSDS,MHSDS,MHSDS,0,0,0,0,10
R1A,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
R1C,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
R1F,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,0,6,12,12,12
R1L,NHS,None,None,MHSDS,MHSDS,MHSDS,MHSDS,0,11,12,12,12
RAT,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RBS,NHS,None,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RCU,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,9,12,12,12,12
RDY,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,0,0
RGD,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RH5,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RHA,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RJ8,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RJX,NHS,KP90,MHSDS,None,None,None,None,3,0,0,0,0
RKL,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RLY,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RMY,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RNN,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,ECDS,5,12,12,6,0
RNU,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RP1,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,11,12,12,12,12
RP7,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RPG,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RQ3,NHS,KP90,Acute,MHSDS,MHSDS,MHSDS,MHSDS,12,12,8,12,11
RQY,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RR7,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RRD,NHS,KP90,MHSDS,MHSDS,None,None,None,12,3,0,0,0
RRE,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RRP,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RT1,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,9
RT2,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,11,12,12,12,12
RT5,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,0,0,12,12,12
RTF,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,11,12,12,12,12
RTQ,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RTV,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,10,12,12,12,12
RV3,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RV5,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RV9,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RVN,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RW1,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RW4,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RW5,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RWK,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RWR,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RWV,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RWX,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,11,12,12
RX2,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RX3,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RX4,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RXA,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,11,12,12,12,12
RXE,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RXG,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,11,11,12
RXM,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RXT,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RXV,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,8,12,12,12,12
RXX,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RXY,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,11,12,12,12,12
RY6,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RY8,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,1,1,6,2,4
RYG,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
RYK,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,11,12,0
RYW,NHS,KP90,Acute,Acute,MHSDS,MHSDS,MHSDS,0,0,3,12,12
TAD,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
TAE,NHS,KP90,MHSDS,None,None,None,None,12,0,0,0,0
TAF,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
TAH,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,12,12,12,12,12
TAJ,NHS,KP90,MHSDS,MHSDS,MHSDS,MHSDS,MHSDS,9,12,12,12,12
"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).write.insertInto(f"{db_output}.pbi_dq_table_2_history")

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMPORARY VIEW All_New_and_Historic_Orgs
 AS
 select distinct Org_Code from $db_output.pbi_dq_table_2_history
 UNION
 select distinct OrgIDProvider as Org_Code from $db_output.dq_mha_submissions_12m where MHA_SUBMISSIONS > 0

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mha_pbi_dq_table2;
 CREATE TABLE         $db_output.mha_pbi_dq_table2 USING DELTA AS
 ---final prep table for power bi dq table 2
 select
 o.Org_Code as Org_Code,
 od.NAME as OrgName,
 coalesce(h.Org_Type, case when (length(o.Org_Code) = 3 and left(o.Org_Code, 1) in ("R", "T")) then "NHS" else "Independent" end) as OrgType,
 coalesce(h.T2_2015_16, "None") as T2_2015_16,
 coalesce(h.T2_2016_17, "None") as T2_2016_17,
 coalesce(h.T2_2017_18, "None") as T2_2017_18,
 coalesce(h.T2_2018_19, "None") as T2_2018_19,
 coalesce(h.T2_2019_20, "None") as T2_2019_20,
 coalesce(h.T2_2020_21, "None") as T2_2020_21,
 coalesce(h.T2_2020_21, "None") as T2_2021_22,
 coalesce(h.MHA_MONTHS_2016_17, 0) as MHA_MONTHS_2016_17,
 coalesce(h.MHA_MONTHS_2017_18, 0) as MHA_MONTHS_2017_18,
 coalesce(h.MHA_MONTHS_2018_19, 0) as MHA_MONTHS_2018_19,
 coalesce(h.MHA_MONTHS_2019_20, 0) as MHA_MONTHS_2019_20,
 coalesce(h.MHA_MONTHS_2020_21, 0) as MHA_MONTHS_2020_21,
 coalesce(y.MHA_SUBMISSIONS, 0) as MHA_MONTHS_2021_22
 from global_temp.All_New_and_Historic_Orgs o
 left join $db_output.mha_rd_org_daily_latest od on o.Org_Code = od.ORG_CODE
 left join $db_output.pbi_dq_table_2_history h on o.Org_Code = h.Org_Code
 left join $db_output.dq_mha_submissions_12m y on o.Org_Code = y.OrgIDProvider

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMPORARY VIEW MHSHeaderOrgs
 ---get the orgs submitted to MHS000Header in the financial year
 AS
 (
   SELECT DISTINCT
     OrgIDProvider AS OrgIDProv,
     UniqMonthID,
     ReportingPeriodEndDate
   FROM $db_source.mhs000header
   WHERE UniqMonthID between $start_month_id and $month_id
 )

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMPORARY VIEW TableNames AS
 ---define user friendly mhsds table names
 (
   SELECT 'MHS001MPI' AS TableName
   UNION ALL SELECT 'MHS101Referral' AS TableName
   UNION ALL SELECT 'MHS401MHActPeriod' AS TableName  
   UNION ALL SELECT 'MHS404CommTreatOrder' AS TableName
   UNION ALL SELECT 'MHS405CommTreatOrderRecall' AS TableName
   UNION ALL SELECT 'MHS501HospProvSpell' AS TableName   
 )

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mhstablecounts;
 CREATE TABLE         $db_output.mhstablecounts USING DELTA AS
 ---calculate the actual counts for each mental health act table in the financial year
 (
   SELECT
     'MHS001MPI' AS TableName,
     UniqMonthID,
     OrgIDProv,
     COUNT(*) AS RowCount
   FROM $db_source.mhs001mpi
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv
   UNION ALL SELECT
     'MHS101Referral' AS TableName,
     UniqMonthID,
     OrgIDProv,
     COUNT(*) AS RowCount
   FROM $db_source.mhs101referral
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv
   UNION ALL SELECT    
     'MHS401MHActPeriod' AS TableName,
     UniqMonthID,
     OrgIDProv,
     COUNT(*) AS RowCount
   FROM $db_source.mhs401mhactperiod
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv
   UNION ALL SELECT    
     'MHS404CommTreatOrder' AS TableName,
     UniqMonthID,
     OrgIDProv,    
     COUNT(*) AS RowCount
   FROM $db_source.mhs404commtreatorder
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv
   UNION ALL SELECT   
     'MHS405CommTreatOrderRecall' AS TableName,
     UniqMonthID,
     OrgIDProv,    
     COUNT(*) AS RowCount
   FROM $db_source.mhs405commtreatorderrecall
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv
   UNION ALL SELECT 
     'MHS501HospProvSpell' AS TableName,
     UniqMonthID,
     OrgIDProv,    
     COUNT(*) AS RowCount
   FROM $db_source.mhs501hospprovspell
   WHERE UniqMonthID between $start_month_id and $month_id
   GROUP BY UniqMonthID,OrgIDProv   
 )
 ;
 optimize $db_output.mhstablecounts

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mhsorgtables;
 CREATE TABLE IF NOT EXISTS $db_output.mhsorgtables 
 USING DELTA AS
 ---get combination of provider and mental health act tables
 (
   SELECT
     OrgIDProv,
     UniqMonthID,
     ReportingPeriodEndDate,
     TableName
   FROM global_temp.MhsHeaderOrgs
   CROSS JOIN global_temp.TableNames
 )
 ;
 optimize $db_output.mhsorgtables

# COMMAND ----------

 %sql
 REFRESH TABLE $db_output.mhsorgtables;
 REFRESH TABLE $db_output.mhstablecounts;
 REFRESH TABLE $db_output.mha_rd_org_daily_latest

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mha_pbi_dq_table3_prep;
 CREATE TABLE         $db_output.mha_pbi_dq_table3_prep USING DELTA AS
 SELECT
   ot.OrgIdProv,
   o.NAME,
   ot.TableName,  
   ot.ReportingPeriodEndDate,
   t.RowCount
   
   FROM $db_output.mhsorgtables ot
   INNER JOIN $db_output.mha_rd_org_daily_latest o ON ot.OrgIDProv = o.ORG_CODE  
   LEFT OUTER JOIN $db_output.mhstablecounts t ON ot.OrgIDProv = t.OrgIDProv 
                                             AND ot.TableName = t.TableName
                                             AND ot.UniqMonthID = t.UniqMonthID

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mha_pbi_dq_table3_prep2;
 CREATE TABLE         $db_output.mha_pbi_dq_table3_prep2 USING DELTA AS
 SELECT
   ReportingPeriodEndDate,
   CASE WHEN OrgIdProv IS NULL THEN 'England' ELSE OrgIdProv END AS ORGANISATION_CODE,
   CASE WHEN OrgIdProv IS NULL THEN 'England' ELSE NAME END AS ORGANISATION_NAME,
   CASE WHEN TableName IS NULL THEN 'Any' ELSE TableName END AS TABLE_NAME,  
   SUM(COALESCE(RowCount, 0)) as Records
   
   FROM $db_output.mha_pbi_dq_table3_prep
 
 -- Add total groups to result set
 GROUP BY
   GROUPING SETS
   (
     (ReportingPeriodEndDate),
     (TableName, ReportingPeriodEndDate),
     (OrgIDProv, NAME, ReportingPeriodEndDate),
     (OrgIDProv, NAME, TableName, ReportingPeriodEndDate)
   )

# COMMAND ----------

 %sql
 DROP TABLE IF EXISTS $db_output.mha_pbi_dq_table3;
 CREATE TABLE         $db_output.mha_pbi_dq_table3 USING DELTA AS
 SELECT
   ORGANISATION_CODE,
   ORGANISATION_NAME,
   TABLE_NAME,  
   'Sum of '+date_format(ReportingPeriodEndDate, 'MMMMM')+' '+date_format(ReportingPeriodEndDate, 'y')+' Final' AS VALUES_STRING,
   Records,
   date_format(ReportingPeriodEndDate, 'MMMMM')+' '+date_format(ReportingPeriodEndDate, 'y')+' Final' AS PERIOD_NAME,
   date_format(ReportingPeriodEndDate, 'dd/MM/yyyy') as PERIOD_END_DATE
   
   FROM $db_output.mha_pbi_dq_table3_prep2