USE [ECDS]

---Set Date Parameters for Financial Year
DECLARE @STARTDATE DATE
SET @STARTDATE = '2021-04-01'

DECLARE @ENDDATE DATE
SET @ENDDATE = '2022-03-31'

---Get ECDS MHA Data Table
IF OBJECT_ID ('tempdb..#2122ECDSTAB') IS NOT NULL
DROP TABLE #2122ECDSTAB

SELECT 
CASE WHEN LEFT(T2.[PROVIDER_SUBMITTED],3) LIKE 'R%' OR LEFT(T2.[PROVIDER_SUBMITTED],3) LIKE 'T%' THEN 'NHS TRUST'
     ELSE 'INDEPENDENT HEALTH PROVIDER' END AS 'ORG_TYPE',
CASE WHEN T2.[PROVIDER_SUBMITTED] LIKE '[A-Za-z][0-9][A-Za-z][0-9][A-Za-z]' THEN T2.[PROVIDER_SUBMITTED]
		 WHEN (T2.[PROVIDER_SUBMITTED] LIKE 'R%' OR T2.[PROVIDER_SUBMITTED] LIKE 'T%') THEN LEFT(T2.[PROVIDER_SUBMITTED],3)
		ELSE T2.[PROVIDER_SUBMITTED]
	END AS 'ORG_CODE',
OD.[NAME] AS 'ORG_NAME',
T1.[RECORD_IDENTIFIER], 
T3.[CLASSIFICATION],
T3.[START_DATE],
T3.[START_TIME],
T3.[EXPIRY_DATE],
T3.[EXPIRY_TIME],
T3.[D_MHA_ORDINAL],
T3.[MODIFIED_DATE],
DENSE_RANK() OVER (PARTITION BY T1.[RECORD_IDENTIFIER] ORDER BY T3.[START_DATE] DESC, T3.[START_TIME] DESC, D_MHA_ORDINAL) AS CLASS_RN ---Needed to get latest CLASSIFICATION OF A RECORD_IDENTIFIER

INTO #2122ECDSTAB

FROM DQ.[DQ_VW_ATT_ATTENDANCE] AS T1 
	LEFT JOIN DQ.[DQ_VW_SYS_SYSTEM] AS T2 
	ON T1.[RECORD_IDENTIFIER] = T2.[RECORD_IDENTIFIER] 
		AND T1.[FILE_LOAD_ID] = T2.[FILE_LOAD_ID]
	LEFT JOIN DQ.[DQ_VW_PAT_MHA] AS T3 
	ON T1.[RECORD_IDENTIFIER] = T3.[RECORD_IDENTIFIER] 
		AND T1.[FILE_LOAD_ID] = T3.[FILE_LOAD_ID]
		AND T3.[CLASSIFICATION] NOT IN ('98', '99')
    LEFT JOIN ECDS.REF.ORG_DAILY as OD
		ON CASE WHEN T2.[PROVIDER_SUBMITTED] LIKE '?#?#?' THEN T2.[PROVIDER_SUBMITTED]
				WHEN (T2.[PROVIDER_SUBMITTED] LIKE 'R%' OR T2.[PROVIDER_SUBMITTED] LIKE 'T%') THEN LEFT(T2.[PROVIDER_SUBMITTED],3)
			ELSE T2.[PROVIDER_SUBMITTED] END = OD.ORG_CODE AND BUSINESS_END_DATE IS NULL AND (
		(ORG_CLOSE_DATE IS NULL AND ORG_OPEN_DATE <= ARRIVAL_DATE) OR (ORG_CLOSE_DATE >= ARRIVAL_DATE AND ORG_OPEN_DATE <= ARRIVAL_DATE))

WHERE T2.[IS_MONTHLY_PUB] = 1 AND 
	T1.[ARRIVAL_DATE] BETWEEN @STARTDATE AND @ENDDATE 
	AND T3.[CLASSIFICATION] IS NOT NULL
	AND T1.[DEPARTMENT_TYPE] != '05'

ORDER BY T1.[RECORD_IDENTIFIER], T3.[START_DATE], T3.[START_TIME]

---Identify which RECORD_IDENTIFIERs have changed CLASSIFICATION codes over time
IF OBJECT_ID ('tempdb..#2122ECDSCHANGE') IS NOT NULL
DROP TABLE #2122ECDSCHANGE

SELECT RECORD_IDENTIFIER, 'Y' as 'CHANGE', COUNT(DISTINCT CLASSIFICATION) AS DIST_CLASS 
INTO #2122ECDSCHANGE
FROM #2122ECDSTAB
GROUP BY RECORD_IDENTIFIER HAVING COUNT(DISTINCT CLASSIFICATION) > 1

---Join back to original ECDS MHA Table to highlight which RECORD_IDENTIFIERs have changed
IF OBJECT_ID ('tempdb..#2122ECDSFINALPREP') IS NOT NULL
DROP TABLE #2122ECDSFINALPREP
SELECT
T1.ORG_TYPE,
T1.ORG_CODE,
T1.ORG_NAME,
T1.RECORD_IDENTIFIER,
T1.CLASSIFICATION,
T1.START_DATE,
T1.START_TIME,
T1.CLASS_RN,
COALESCE(T2.CHANGE, 'N') AS 'CHANGE'
INTO #2122ECDSFINALPREP
FROM #2122ECDSTAB T1
LEFT JOIN #2122ECDSCHANGE T2 ON T1.RECORD_IDENTIFIER = T2.RECORD_IDENTIFIER
ORDER BY RECORD_IDENTIFIER, CLASS_RN

---Get Minimum CLASS_RN for each RECORD_IDENTIFIER and CLASSIFICATION (where there was a change)
IF OBJECT_ID ('tempdb..#2122ECDSCHANGEPREP') IS NOT NULL
DROP TABLE #2122ECDSCHANGEPREP
SELECT DISTINCT RECORD_IDENTIFIER, CLASSIFICATION, MIN(CLASS_RN) AS CLASS_RN 
INTO #2122ECDSCHANGEPREP
FROM #2122ECDSFINALPREP 
WHERE CHANGE = 'Y' 
GROUP BY RECORD_IDENTIFIER, CLASSIFICATION
ORDER BY RECORD_IDENTIFIER, CLASS_RN

---Use CLASS_RN to get new ordered rank
IF OBJECT_ID ('tempdb..#2122ECDSCHANGEPREPPRE') IS NOT NULL
DROP TABLE #2122ECDSCHANGEPREPPRE
SELECT DISTINCT RECORD_IDENTIFIER, CLASSIFICATION, 
DENSE_RANK() OVER (PARTITION BY RECORD_IDENTIFIER ORDER BY CLASS_RN) AS CLASS_RN
INTO #2122ECDSCHANGEPREPPRE
FROM #2122ECDSCHANGEPREP
ORDER BY RECORD_IDENTIFIER, CLASS_RN

---Join table above to itself to get the Previous and Final Classification for RECORD_IDENTIFIERs which changed CLASSIFICATION
IF OBJECT_ID ('tempdb..#2122ECDSCHANGEPREP2') IS NOT NULL
DROP TABLE #2122ECDSCHANGEPREP2
SELECT DISTINCT 
F.RECORD_IDENTIFIER,
P.CLASSIFICATION AS PREV_CLASS,
F.CLASSIFICATION AS FINAL_CLASS
INTO #2122ECDSCHANGEPREP2
FROM (SELECT DISTINCT RECORD_IDENTIFIER, CLASSIFICATION, CLASS_RN FROM #2122ECDSCHANGEPREPPRE) F
LEFT JOIN (SELECT DISTINCT RECORD_IDENTIFIER, CLASSIFICATION, CLASS_RN FROM #2122ECDSCHANGEPREPPRE) P ON F.RECORD_IDENTIFIER = P.RECORD_IDENTIFIER AND P.CLASS_RN = F.CLASS_RN + 1
WHERE P.CLASSIFICATION IS NOT NULL
ORDER BY F.RECORD_IDENTIFIER

---Final Table which considers RECORD_IDENTIFIERS which didn't change CLASSIFICATION and those that did (2# metrics)
IF OBJECT_ID ('tempdb..#2122ECDSSECTIONS') IS NOT NULL
DROP TABLE #2122ECDSSECTIONS
SELECT
NC.ORG_TYPE,
NC.ORG_CODE,
NC.ORG_NAME,
SUM(CASE WHEN [CLASSIFICATION] = 02 THEN 1 ELSE 0 END) AS '1#1_Section_2',
SUM(CASE WHEN [CLASSIFICATION] = 03 THEN 1 ELSE 0 END) AS '1#2_Section_3',
SUM(CASE WHEN [CLASSIFICATION] = 20 THEN 1 ELSE 0 END) AS '1#3_Section_136',
SUM(CASE WHEN [CLASSIFICATION] = 04 THEN 1 ELSE 0 END) AS '1#4_Section_4',
SUM(CASE WHEN [CLASSIFICATION] = 05 THEN 1 ELSE 0 END) AS '1#5_Section_5(2)',
SUM(CASE WHEN [CLASSIFICATION] = 06 THEN 1 ELSE 0 END) AS '1#6_Section_5(4)',
SUM(CASE WHEN [CLASSIFICATION] = 07 THEN 1 ELSE 0 END) AS '1#7_Section_35',
SUM(CASE WHEN [CLASSIFICATION] = 08 THEN 1 ELSE 0 END) AS '1#8_Section_36',
SUM(CASE WHEN [CLASSIFICATION] = 09 THEN 1 ELSE 0 END) AS '1#9_Section_37_with_section_41_restrictions',
SUM(CASE WHEN [CLASSIFICATION] = 10 THEN 1 ELSE 0 END) AS '1#10_Section_37',
SUM(CASE WHEN [CLASSIFICATION] = 12 THEN 1 ELSE 0 END) AS '1#11_Section_38',
SUM(CASE WHEN [CLASSIFICATION] = 13 THEN 1 ELSE 0 END) AS '1#12_Section_44',
SUM(CASE WHEN [CLASSIFICATION] = 14 THEN 1 ELSE 0 END) AS '1#13_Section_46',
SUM(CASE WHEN [CLASSIFICATION] = 15 THEN 1 ELSE 0 END) AS '1#14_Section_47_with_section_49_restrictions',
SUM(CASE WHEN [CLASSIFICATION] = 16 THEN 1 ELSE 0 END) AS '1#15_Section_47',
SUM(CASE WHEN [CLASSIFICATION] = 17 THEN 1 ELSE 0 END) AS '1#16_Section_48 with_section_49_restrictions',
SUM(CASE WHEN [CLASSIFICATION] = 18 THEN 1 ELSE 0 END) AS '1#17_Section_48',
SUM(CASE WHEN [CLASSIFICATION] = 19 THEN 1 ELSE 0 END) AS '1#19_Section_135',
SUM(CASE WHEN [CLASSIFICATION] = 31 THEN 1 ELSE 0 END) AS '1#20_Criminal_Procedure(Insanity)_Act_1964',
SUM(CASE WHEN [CLASSIFICATION] = 32 THEN 1 ELSE 0 END) AS '1#21_Formally_detained_under_other_acts',
SUM(CASE WHEN [CLASSIFICATION] = 35 THEN 1 ELSE 0 END) AS '1#22_Section_7',
SUM(CASE WHEN [CLASSIFICATION] = 36 THEN 1 ELSE 0 END) AS '1#23_Section_37',
SUM(CASE WHEN [CLASSIFICATION] = 37 THEN 1 ELSE 0 END) AS '1#24_Section_45A#-(Limited direction in force)',
SUM(CASE WHEN [CLASSIFICATION] = 38 THEN 1 ELSE 0 END) AS '1#25_Section_45A_(Limitation direction ended)',
-------------------------------------------------------------------------------------------------------------------------
SUM(CASE WHEN C.PREV_CLASS = 01 AND C.FINAL_CLASS = 06 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#1_Informal_to_5_(4)',
SUM(CASE WHEN C.PREV_CLASS = 01 AND C.FINAL_CLASS = 05 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#2_Informal_to_5_(2)',
SUM(CASE WHEN C.PREV_CLASS = 01 AND C.FINAL_CLASS = 02 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#3_Informal_to_2',
SUM(CASE WHEN C.PREV_CLASS = 20 AND C.FINAL_CLASS = 02 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#4_Section_136_to_2',
SUM(CASE WHEN C.PREV_CLASS = 05 AND C.FINAL_CLASS = 02 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#5_Section_5(2)_to_2',
SUM(CASE WHEN C.PREV_CLASS = 01 AND C.FINAL_CLASS = 03 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#6_Informal_to_3',
SUM(CASE WHEN C.PREV_CLASS = 05 AND C.FINAL_CLASS = 03 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#7_Section_5_(2)_to_3',
SUM(CASE WHEN C.PREV_CLASS = 20 AND C.FINAL_CLASS = 03 AND CLASS_RN = 1 THEN 1 ELSE 0 END) AS '2#8_Section_136_to_3'

INTO #2122ECDSSECTIONS
FROM #2122ECDSFINALPREP NC
LEFT JOIN #2122ECDSCHANGEPREP2 C ON NC.RECORD_IDENTIFIER = C.RECORD_IDENTIFIER
GROUP BY ORG_CODE, ORG_TYPE, ORG_NAME
ORDER BY ORG_CODE

---Final output unsuppressed
IF OBJECT_ID ('tempdb..#2122ECDSFINAL') IS NOT NULL
DROP TABLE #2122ECDSFINAL
SELECT
ORG_TYPE,
ORG_CODE,
ORG_NAME,
SUM(E.[1#1_Section_2] + E.[1#2_Section_3] + E.[1#7_Section_35] + E.[1#8_Section_36] + E.[1#9_Section_37_with_section_41_restrictions] + E.[1#10_Section_37] + E.[1#24_Section_45A#-(Limited direction in force)] + E.[1#25_Section_45A_(Limitation direction ended)] + E.[1#14_Section_47_with_section_49_restrictions] + E.[1#15_Section_47] + E.[1#16_Section_48 with_section_49_restrictions] + E.[1#11_Section_38] + E.[1#12_Section_44] + E.[1#14_Section_47_with_section_49_restrictions] + E.[1#20_Criminal_Procedure(Insanity)_Act_1964] + E.[1#21_Formally_detained_under_other_acts] + E.[1#22_Section_7] + E.[1#23_Section_37]) AS 'All detentions',
SUM(E.[1#1_Section_2] + E.[1#2_Section_3] + E.[1#7_Section_35] + E.[1#8_Section_36] + E.[1#9_Section_37_with_section_41_restrictions] + E.[1#10_Section_37] + E.[1#24_Section_45A#-(Limited direction in force)] + E.[1#25_Section_45A_(Limitation direction ended)] + E.[1#14_Section_47_with_section_49_restrictions] + E.[1#15_Section_47] + E.[1#16_Section_48 with_section_49_restrictions] + E.[1#11_Section_38] + E.[1#12_Section_44] + E.[1#14_Section_47_with_section_49_restrictions] + E.[1#20_Criminal_Procedure(Insanity)_Act_1964] + E.[1#21_Formally_detained_under_other_acts] + E.[1#22_Section_7] + E.[1#23_Section_37]) AS 'Detentions on admission to hospital',
SUM(E.[1#1_Section_2] + E.[1#2_Section_3]) AS 'All detentions under Part 2',
SUM(E.[1#1_Section_2]) AS 'Section 2',
SUM(E.[1#2_Section_3]) AS 'Section 3',
SUM(E.[1#19_Section_135] + E.[1#3_Section_136] + E.[1#4_Section_4] + E.[1#5_Section_5(2)] + E.[1#6_Section_5(4)]) AS 'Short term orders',
SUM(E.[1#19_Section_135] + E.[1#3_Section_136]) AS 'All place of safety orders',
SUM(E.[1#19_Section_135]) AS 'Section 135',
SUM(E.[1#3_Section_136]) AS 'Section 136',
SUM(E.[1#4_Section_4]) AS 'Section 4',
SUM(E.[1#5_Section_5(2)] + E.[1#6_Section_5(4)]) AS 'All uses of section 5',
SUM(E.[1#5_Section_5(2)]) AS 'Section 5(2)',
SUM(E.[1#6_Section_5(4)]) AS 'Section 5(4)',
SUM(E.[1#7_Section_35] + E.[1#8_Section_36] + E.[1#9_Section_37_with_section_41_restrictions] + E.[1#10_Section_37] + E.[1#24_Section_45A#-(Limited direction in force)] + E.[1#25_Section_45A_(Limitation direction ended)] + E.[1#14_Section_47_with_section_49_restrictions] + E.[1#15_Section_47] + E.[1#16_Section_48 with_section_49_restrictions] + E.[1#11_Section_38] + E.[1#12_Section_44] + E.[1#14_Section_47_with_section_49_restrictions]) AS 'All detentions under part 3',
SUM(E.[1#7_Section_35]) AS 'Section 35',
SUM(E.[1#8_Section_36]) AS 'Section 36',
SUM(E.[1#9_Section_37_with_section_41_restrictions]) AS 'Section 37 with section 41 restrictions',
SUM(E.[1#10_Section_37]) AS 'Section 37',
SUM(E.[1#24_Section_45A#-(Limited direction in force)] + E.[1#25_Section_45A_(Limitation direction ended)]) AS 'Section 45A',
SUM(E.[1#14_Section_47_with_section_49_restrictions]) AS 'Section 47 with section 49 restrictions',
SUM(E.[1#15_Section_47]) AS 'Section 47',
SUM(E.[1#16_Section_48 with_section_49_restrictions]) AS 'Section 48 with section 49 restrictions',
SUM(E.[1#11_Section_38] + E.[1#12_Section_44] + E.[1#14_Section_47_with_section_49_restrictions]) AS 'Detentions under other sections 38, 44 and 46',
SUM(E.[1#20_Criminal_Procedure(Insanity)_Act_1964] + E.[1#21_Formally_detained_under_other_acts] + E.[1#22_Section_7] + E.[1#23_Section_37]) AS 'Detentions under other acts' 
INTO #2122ECDSFINAL
FROM #2122ECDSSECTIONS E 
GROUP BY ORG_TYPE, ORG_CODE, ORG_NAME
ORDER BY ORG_CODE

SELECT * FROM #2122ECDSFINAL